allure_environment:
  URL: https://github.com/chineseluo/opensourcetest
  description: "阿木木的UI自动化测试框架"
  username: 848257135@qq.com
  version: V0.2.0

test_info:
  test_URL: https://getsuwo.com/?n=fastCat.fcFrontSnail.NewFront.NewFront.PCLoginPage

selenium_config:
  #配置selenium_hub_url，指定启用本地的selenium_hub还是远程docker容器的selenium_hub
  selenium_hub_url: "http://127.0.0.1:4444/wd/hub"